# Generated by Django 2.1.1 on 2020-01-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.IntegerField(blank=True),
        ),
    ]
