# Generated by Django 2.1.1 on 2020-01-23 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200123_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='cust_name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='cust_name',
        ),
    ]
