# Generated by Django 2.1.1 on 2020-01-23 21:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20200123_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_id', models.IntegerField(blank=True)),
                ('repair_item', models.CharField(max_length=100)),
                ('repair_model', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('setup_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('repair_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('cust_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='crm.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='cust_name',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
