# Generated by Django 2.1.1 on 2020-01-23 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20200123_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Issue', models.CharField(max_length=100)),
                ('severity', models.CharField(max_length=50)),
                ('cust_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='crm.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='repair',
            name='setup_time',
        ),
        migrations.AddField(
            model_name='tickets',
            name='repair_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='crm.Repair'),
        ),
    ]
