# Generated by Django 2.1.1 on 2020-01-23 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20200123_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='repair_id',
            field=models.ForeignKey(blank=True, default='repair_id', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='crm.Repair'),
        ),
    ]
