# Generated by Django 2.1.1 on 2020-02-12 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20200123_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='setup_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
