# Generated by Django 2.1.1 on 2020-02-12 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20200212_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='setup_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
